### ISSUE TITLE
Buttons for calling print and export of the transaction file do not work

### ISSUE THREAD

**Issue by IgorGer55** [persistenceOne/pStake-bugBounty#19]
**Buttons for calling print and export of the transaction file do not work**
On the transactions tab at the top there are buttons for printing and exporting the transaction file.
First note, they don't work. If you click on them with the mouse, then nothing happens. Second note, the titles of these buttons are half-visible to the user. Part of the name is hidden by interface elements.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://alpha.pstake.finance/transactions'
2. Click on button "Print" or "Export 
3. Nothing happens

**Expected behaviour**
The user is confident that he will be able to take advantage of these functions, and will be angry if he finds that they do not work.

**Screenshots**
![alt text](https://github.com/IgorGer55/Pickchers/blob/main/%D0%92%D0%B5%D1%87%D0%B5%D1%80%203.jpg?raw=true)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Google chrome
 - Version 91.0.4472.114

**Ethereum address**
0xCf7FB3AdC0A9A4E6F7Caff2ca8C365325Fd19277

**Criticality Assessment**
Please pick one:
- [ ] **High**:	An issue that might cause immediate loss of the funds or permanent/severe damage of the protocol state
- [ ] **Medium**:	An issue that might theoretically cause minimal loss of funds damage the protocol state or cause severe user dissatisfaction
- [X] **Low**:	An issue that might cause user dissatisfaction or minimal failure of the application

**Checklist**
- [X] The reported issue is in the [scope](https://docs.pstake.finance/Program_Scope/) of the pStake BugBounty program.
- [X] This issue has not been reported before.
- [X] The ethereum address filled in is valid.

**Comment by kombos** [comment]
This issue has been reproduced.

**Comment by kombos** [comment]
please provide your eth address to receive your bounty

**Comment by IgorGer55** [comment]
> пожалуйста, предоставьте свой адрес eth, чтобы получить награду
Hi! My wallet 
0xCf7FB3AdC0A9A4E6F7Caff2ca8C365325Fd19277

**Comment by madhursatija** [comment]
Rewards sent for both the bugs:
https://etherscan.io/tx/0x36c4540638b9c9283fc301838cc567e4ee640ee5ceb41d912e382edc6bf5640f
