### ISSUE TITLE
Deposit search does not work

### ISSUE THREAD

**Issue by IgorGer55** [persistenceOne/pStake-bugBounty#20]
**Deposit search does not work**
Searching for wallet replenishment transaction on the transactions page does not work. If you enter the name of the operation, it finds nothing. Although this operation was performed more than once.

**To Reproduce**
Steps to reproduce the behaviour:
1) Go to 'Transactions' page https://alpha.pstake.finance/transactions.
2) Make sure you have 'deposit' type transactions.
3) Type 'deposit' and it doesn't display any.

**Expected behaviour**
The user expects the search to work as expected and will be upset if it does not.

**Screenshots**
![alt text](https://github.com/IgorGer55/Pickchers/blob/main/66.jpg?raw=true)
![alt text](https://github.com/IgorGer55/Pickchers/blob/main/666.jpg?raw=true)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Google Chrome
 - Version  91.0.4472.114

**Ethereum address**
0xCf7FB3AdC0A9A4E6F7Caff2ca8C365325Fd19277

**Criticality Assessment**
Please pick one:
- [ ] **High**:	An issue that might cause immediate loss of the funds or permanent/severe damage of the protocol state
- [ ] **Medium**:	An issue that might theoretically cause minimal loss of funds damage the protocol state or cause severe user dissatisfaction
- [X] **Low**:	An issue that might cause user dissatisfaction or minimal failure of the application

**Checklist**
- [x] The reported issue is in the [scope](https://docs.pstake.finance/Program_Scope/) of the pStake BugBounty program.
- [x] This issue has not been reported before.
- [x] The ethereum address filled in is valid.

**Comment by kombos** [comment]
This issue has been reproduced.

**Comment by madhursatija** [comment]
Rewards sent for both the bugs:
https://etherscan.io/tx/0x36c4540638b9c9283fc301838cc567e4ee640ee5ceb41d912e382edc6bf5640f
