### ISSUE TITLE
User gets error when closes WalletConnect window while Metamask is connected to Ropsten network

### ISSUE THREAD

**Issue by boddy21** [persistenceOne/pStake-bugBounty#22]
Describe the bug
When click Close (x) button on WalletConnect window, user gets Network error even if Ropsten network is already selected in Metamask.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect to MetaMask and choose Ropsten Test Network
2. Go to 'https://alpha.pstake.finance/' 
3. Click on 'WalletConnect' button
4. Click Close (x) button
5. Result: Wallet looks connected but confusing 'Network Id Mismatch' error appears on screen. 

Expected behaviour
User should not see Network error since he is already connected to correct Ropsten network.

**Screenshots**
![2021-06-21_01-31-22](https://user-images.githubusercontent.com/1258770/122690142-7483f400-d230-11eb-8cbb-8320b5085ac0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome
 - Version  91.0.4472.106

**Additional context**
Video url - https://www.screencast.com/t/Jd14f3Vy

**Ethereum address**
0x25F1bA6a6075B683e4fceDd08eDcF84B2F6bdFD5

**Criticality Assessment**
Please pick one:
- [ ] **High**:	An issue that might cause immediate loss of the funds or permanent/severe damage of the protocol state
- [ ] **Medium**:	An issue that might theoretically cause minimal loss of funds damage the protocol state or cause severe user dissatisfaction
- [x] **Low**:	An issue that might cause user dissatisfaction or minimal failure of the application

**Checklist**
- [x] The reported issue is in the [scope](https://docs.pstake.finance/Program_Scope/) of the pStake BugBounty program.
- [x] This issue has not been reported before.
- [x] The ethereum address filled in is valid.

**Comment by kombos** [comment]
since choosing a wallet is considered a mandatory step, refusing to choose any wallet should be notified. This is true even for how metamask internally works. rejecting metamask connection once leads to an internal error generating in it the second time. But will consider, for the sake of UX for users, if we can directly bring the user back to the list of wallets. This is not a bug but a design choice.

**Comment by boddy21** [comment]
The issue here that user got 'Network Id Mismatch' error when Metamask is already connected to Ropsten network. Metamask should not refuse the connected with such error if all conditions are satisfied (user is already logged in to Metamask and Ropsten network is selected). Please review this issue from this perspective.

**Comment by boddy21** [comment]
> since choosing a wallet is considered a mandatory step, refusing to choose any wallet should be notified. This is true even for how metamask internally works. rejecting metamask connection once leads to an internal error generating in it the second time. But will consider, for the sake of UX for users, if we can directly bring the user back to the list of wallets. This is not a bug but a design choice.

**Comment by boddy21** [comment]
Closed by mistake please view my previous comment. Thanks.

**Comment by kombos** [comment]
This issue has been reproduced and considered as change worthy.

**Comment by kombos** [comment]
please provide your eth address to receive your bounty

**Comment by kombos** [comment]
please provide your ethereum address to get your bounty reward asap before the time expires. tx.

**Comment by madhursatija** [comment]
Rewards sent on the ETH address submitted: 
https://etherscan.io/tx/0x1145cc1f52aebbc9e795cb53fa8116828fe855e8e60ea0a60b675d9c7c1f9ac6
