### ISSUE TITLE
Unnecessary Modal Appears after Metamask Wallet Connection

### ISSUE THREAD

**Issue by cybertronprime** [persistenceOne/pStake-bugBounty#24]
**Describe the bug**
So whenever metamask is connected, we see a small Modal popping up for a few Seconds "stating that there is Network ID Mismatch" which goes away by itself but shouldnt have popped up , as its a successful process..
After reloading the web page, we are needed to connect to wallet again, which is a unnecessary step as we have already connected to the wallet and that should be save some where in the State or Localstorage,

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Pstake website'
2. Launch Alpha.pstake.finance
3. connect Your metamask
4. After Successful connection, you will see Network ID Mismatch Modal for a few seconds.
5. It will go away automatically, but should not be there in any case.
6. Reload the page, now you will need to connect wallet again, and that Modal will appear for a few moments again .

**Expected behavior**
The error should not have occurred , and also we should not need to connect to walled on every reload, as its irritating for any end user,

**Screenshots**
https://drive.google.com/drive/folders/1Qolqx4_-544NzyDuXc9KWYPSosF1I76Q?usp=sharing

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - Chrome
 - Latest Build

**Ethereum address**
0xcD988D0DB4B3e7C4A666C8A2fB42E4447E8f11df

**Criticality Assessment**
Please pick one:
- [ ] **High**:	An issue that might cause immediate loss of the funds or permanent/severe damage of the protocol state
- [ ] **Medium**:	An issue that might theoretically cause minimal loss of funds damage the protocol state or cause severe user dissatisfaction
- [x] Low:	An issue that might cause user dissatisfaction or minimal failure of the application

**Checklist**
- [x] The reported issue is in the [scope](https://docs.pstake.finance/Program_Scope/) of the pStake BugBounty program.
- [x] This issue has not been reported before.
- [x] The ethereum address filled in is valid.

**Comment by kombos** [comment]
this has been reproduced.

**Comment by cybertronprime** [comment]
Reproduced by someone else?

**Comment by kombos** [comment]
please provide your eth address to receive your bounty

**Comment by cybertronprime** [comment]
My ethereum Address : 0xcD988D0DB4B3e7C4A666C8A2fB42E4447E8f11df

Thanks

**Comment by madhursatija** [comment]
Rewards sent: 
https://etherscan.io/tx/0xe1cf69e04c2400264e8f00636c7014a864430ae96ac96c47c85dd5b8b781c690
