### ISSUE TITLE
Unstake Amount increase too much Total Unbonding Tokens Issue

### ISSUE THREAD

**Issue by igtumt** [persistenceOne/pStake-bugBounty#34]
**Describe the bug**

Hello, at first i have 5 amount pAtom total unbonding tokens, when i tried to unstake a minutes ago about amount 5 , i accidentally unstake 5 and then click on unstake 5 again before the transaction finished in the metamask. And then i see that my unbonding tokens show 75 pAtom which was about 5 amount so i got more pAtom which how its happen i dont understand. And now it added 5 more and it become 80 amount.

**To Reproduce**
Steps to reproduce the behaviour:

**2. Click on 'Unstake button'**

**Expected behaviour**
Normally it should add 5+5 amount or 5+5+5 amount max but it increase too much amount.

**Screenshots**
![image](https://user-images.githubusercontent.com/72981654/124618740-b6dc4080-de80-11eb-8513-ea9a4bf61e14.png)

**Desktop (please complete the following information):**
 
 **- Browser [e.g. chrome, safari] i use firefox**
 

**Additional context**
i added transactions view here to show my balance is wrong.
![pstake3](https://user-images.githubusercontent.com/72981654/124622420-c741ea80-de83-11eb-9023-f2a883b02f91.JPG)
![pstake2](https://user-images.githubusercontent.com/72981654/124622448-cd37cb80-de83-11eb-9bb7-c4694bea42e6.JPG)
I can give more info if you need. Thanks.

**Ethereum address**
Your ethereum wallet address to receive the bounty on reporting a valid bug.

0xbcAa74F9ac5f33d7e5a04EDBb5AaF223195B1e81

**Criticality Assessment**
Please pick one:
- [x] **High**:	An issue that might cause immediate loss of the funds or permanent/severe damage of the protocol state
- [ ] **Medium**:	An issue that might theoretically cause minimal loss of funds damage the protocol state or cause severe user dissatisfaction
- [ ] **Low**:	An issue that might cause user dissatisfaction or minimal failure of the application

**Checklist**
- [x] The reported issue is in the [scope](https://docs.pstake.finance/Program_Scope/) of the pStake BugBounty program.
- [x] This issue has not been reported before.
- [x] The ethereum address filled in is valid.

**Comment by igtumt** [comment]
after some hours pATOM in total unbonding tokes looks normal but not correct amount i guess you can check from transactions.
![image](https://user-images.githubusercontent.com/72981654/124639616-0cbae380-de95-11eb-841b-e9c462fa0229.png)

**Comment by kombos** [comment]
the data in blockchain is correct only. the data displayed in pstake app seems to show wrong because of multiple duplicate events read. This issue has been identified but since this is only an issue of display in the app, while the actual data in the blockchain is correct, this has been categorized as a low priority issue since there is no loss of tokens or funds of any sort.

**Comment by kombos** [comment]
please provide your ethereum address at the earliest to process bounty.

**Comment by igtumt** [comment]
hi, thank you for explanation. This is my eth address 0xbcAa74F9ac5f33d7e5a04EDBb5AaF223195B1e81

**Comment by madhursatija** [comment]
Rewards sent: 
https://etherscan.io/tx/0x30f6a47bc8a63f3ab2d3d5ee9b9d0b6c9eb46b273cd69e6c0cd0dc7ed30c1fe9
