### ISSUE TITLE
Transactions Filter Not Working Properly

### ISSUE THREAD

**Issue by napelvs** [persistenceOne/pStake-bugBounty#6]
**Describe the bug**
**Disclaimer: Not sure if it's within the scope of the 'Bug-Bounty' program.**
When searching for "Redeem" type transactions on the "Transactions" page, it doesn't work properly. e.g. typing 'Red' correctly displays all the 'Redeem' type transactions, but typing 'Rede', 'Redee', or 'Redeem doesn't display anything.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Transactions' page.
2. Make sure you have 'Redeem' type transactions.
3. Type 'Red', it should display all the 'Redeem' transactions.
4. Type 'Rede', 'Redee', or 'Redeem' and it doesn't display any.

**Expected behaviour**
Display all 'Redeem' type transactions.

**Screenshots**
![image](https://user-images.githubusercontent.com/45354872/122084539-d213dd00-cdf9-11eb-8519-69c7804ef1ee.png)
![image](https://user-images.githubusercontent.com/45354872/122084585-db04ae80-cdf9-11eb-9422-7d7bd5bdd58a.png)
![image](https://user-images.githubusercontent.com/45354872/122084622-e3f58000-cdf9-11eb-85c5-8f9276cea740.png)
![image](https://user-images.githubusercontent.com/45354872/122084645-e9eb6100-cdf9-11eb-8403-a2ce700c6054.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: V1.25.72 

**Ethereum address**
0x3f3eb8aad1b3c4a8184f82dc0e471b5641c6bfdc

**Criticality Assessment**
Please pick one:
- [ ] **High**:	An issue that might cause immediate loss of the funds or permanent/severe damage of the protocol state
- [ ] **Medium**:	An issue that might theoretically cause minimal loss of funds damage the protocol state or cause severe user dissatisfaction
- [x] **Low**:	An issue that might cause user dissatisfaction or minimal failure of the application

**Checklist**
- [x] The reported issue is in the [scope](https://docs.pstake.finance/pStake/Program_Scope/) of the pStake BugBounty program.
- [x] This issue has not been reported before.
- [x] The ethereum address filled in is valid.

**Comment by kombos** [comment]
> **Describe the bug**
> **Disclaimer: Not sure if it's within the scope of the 'Bug-Bounty' program.**
> When searching for "Redeem" type transactions on the "Transactions" page, it doesn't work properly. e.g. typing 'Red' correctly displays all the 'Redeem' type transactions, but typing 'Rede', 'Redee', or 'Redeem doesn't display anything.
> 
> **To Reproduce**
> Steps to reproduce the behaviour:
> 
> 1. Go to 'Transactions' page.
> 2. Make sure you have 'Redeem' type transactions.
> 3. Type 'Red', it should display all the 'Redeem' transactions.
> 4. Type 'Rede', 'Redee', or 'Redeem' and it doesn't display any.
> 
> **Expected behaviour**
> Display all 'Redeem' type transactions.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/45354872/122084539-d213dd00-cdf9-11eb-8519-69c7804ef1ee.png)
> ![image](https://user-images.githubusercontent.com/45354872/122084585-db04ae80-cdf9-11eb-9422-7d7bd5bdd58a.png)
> ![image](https://user-images.githubusercontent.com/45354872/122084622-e3f58000-cdf9-11eb-85c5-8f9276cea740.png)
> ![image](https://user-images.githubusercontent.com/45354872/122084645-e9eb6100-cdf9-11eb-8403-a2ce700c6054.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows
> * Browser: Brave
> * Version: V1.25.72
> 
> **Ethereum address**
> 0x3f3eb8aad1b3c4a8184f82dc0e471b5641c6bfdc
> 
> **Criticality Assessment**
> Please pick one:
> 
> * [ ]  **High**:	An issue that might cause immediate loss of the funds or permanent/severe damage of the protocol state
> * [ ]  **Medium**:	An issue that might theoretically cause minimal loss of funds damage the protocol state or cause severe user dissatisfaction
> * [x]  **Low**:	An issue that might cause user dissatisfaction or minimal failure of the application
> 
> **Checklist**
> 
> * [x]  The reported issue is in the [scope](https://docs.pstake.finance/pStake/Program_Scope/) of the pStake BugBounty program.
> * [x]  This issue has not been reported before.
> * [x]  The ethereum address filled in is valid.

we have reproduced this issue and have added this in our tracker. Thank you for your feedback. We will get back to you shortly after discussing and taking actions on this.

**Comment by kombos** [comment]
@napelvs, please provide your eth address to receive your bounty for bug tracking

**Comment by napelvs** [comment]
> @napelvs, please provide your eth address to receive your bounty for bug tracking

Not sure in what tokens you send the rewards, but in case it is not ETH use the Metamask wallet address. If it's ETH, please use the Binance ETH address.

Binance: 0x3f3eb8aad1b3c4a8184f82dc0e471b5641c6bfdc
Metamask: 0x6c2b8F1C4BB1501049455f1d488ADe6b42Ea2adF

**Comment by madhursatija** [comment]
Transaction done for both the bugs: https://etherscan.io/tx/0xb0e402a29cc2eafa25d080f60ee082ad3029171c064843eb9f986e36f5a57bc9
