### ISSUE TITLE
Smartphone Sidebars Not Working

### ISSUE THREAD

**Issue by napelvs** [persistenceOne/pStake-bugBounty#8]
**Describe the bug**
After connecting a wallet, I can't access any of the side menus. I tried clicking on the 'burger' menu but it doesn't work. Sometimes, after spamming on the icon, it appears and disappears in milliseconds. Because of this, a user accessing the application with a smartphone can't use it at all.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'alpha.pstake.finance' and connect your wallet.
2. Click on the 'burger' menu icon. It should either not appear or appear for a very short time.
2. Click on the right side icon which shows tokens balance. It should either not appear or appear for a very short time.

**Expected behaviour**
Access the wrap/stake/transactions pages and have information about the tokens available on the wallet.

**Smartphone (please complete the following information):**
 - Device: Xiaomi mi 9T
 - OS: Android 10 / MIUI Global 12.0.5
 - Browser: Chrome
 - Version: 91.0.4472.101

**Ethereum address**
0x3f3eb8aad1b3c4a8184f82dc0e471b5641c6bfdc

**Criticality Assessment**
Please pick one:
- [ ] **High**:	An issue that might cause immediate loss of the funds or permanent/severe damage of the protocol state
- [x] **Medium**:	An issue that might theoretically cause minimal loss of funds damage the protocol state or cause severe user dissatisfaction
- [ ] **Low**:	An issue that might cause user dissatisfaction or minimal failure of the application

**Checklist**
- [x] The reported issue is in the [scope](https://docs.pstake.finance/Program_Scope/) of the pStake BugBounty program.
- [x] This issue has not been reported before.
- [x] The ethereum address filled in is valid.

**Comment by madhursatija** [comment]
Transaction done for both the bugs: https://etherscan.io/tx/0xb0e402a29cc2eafa25d080f60ee082ad3029171c064843eb9f986e36f5a57bc9
